/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Map */

#ifndef _Included_Map
#define _Included_Map
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Map
 * Method:    manageReadMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Map_manageReadMap
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Map
 * Method:    manageLoadMap
 * Signature: ([[C)V
 */
JNIEXPORT void JNICALL Java_Map_manageLoadMap
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Map
 * Method:    manageSetWin
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Map_manageSetWin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Map
 * Method:    manageSetName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Map_manageSetName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
